// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/jiachen/Git/mgcache/test/mock/storage/mock_interface.go

// Package mock_mock_storage is a generated GoMock package.
package mock_mock_storage
