// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/jiachen/Git/mgcache/storage/interface.go

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIStorage is a mock of IStorage interface.
type MockIStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIStorageMockRecorder
}

// MockIStorageMockRecorder is the mock recorder for MockIStorage.
type MockIStorageMockRecorder struct {
	mock *MockIStorage
}

// NewMockIStorage creates a new mock instance.
func NewMockIStorage(ctrl *gomock.Controller) *MockIStorage {
	mock := &MockIStorage{ctrl: ctrl}
	mock.recorder = &MockIStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStorage) EXPECT() *MockIStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIStorage) Get(key string, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockIStorageMockRecorder) Get(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIStorage)(nil).Get), key, value)
}

// GetBytes mocks base method.
func (m *MockIStorage) GetBytes(key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBytes", key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBytes indicates an expected call of GetBytes.
func (mr *MockIStorageMockRecorder) GetBytes(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBytes", reflect.TypeOf((*MockIStorage)(nil).GetBytes), key)
}

// Invalidate mocks base method.
func (m *MockIStorage) Invalidate(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockIStorageMockRecorder) Invalidate(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockIStorage)(nil).Invalidate), key)
}

// Refresh mocks base method.
func (m *MockIStorage) Refresh(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockIStorageMockRecorder) Refresh(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockIStorage)(nil).Refresh), key)
}

// Set mocks base method.
func (m *MockIStorage) Set(key string, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockIStorageMockRecorder) Set(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockIStorage)(nil).Set), key, value)
}

// MockIFallbackStorage is a mock of IFallbackStorage interface.
type MockIFallbackStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIFallbackStorageMockRecorder
}

// MockIFallbackStorageMockRecorder is the mock recorder for MockIFallbackStorage.
type MockIFallbackStorageMockRecorder struct {
	mock *MockIFallbackStorage
}

// NewMockIFallbackStorage creates a new mock instance.
func NewMockIFallbackStorage(ctrl *gomock.Controller) *MockIFallbackStorage {
	mock := &MockIFallbackStorage{ctrl: ctrl}
	mock.recorder = &MockIFallbackStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFallbackStorage) EXPECT() *MockIFallbackStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIFallbackStorage) Get(key string, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockIFallbackStorageMockRecorder) Get(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIFallbackStorage)(nil).Get), key, value)
}

// GetBytes mocks base method.
func (m *MockIFallbackStorage) GetBytes(key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBytes", key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBytes indicates an expected call of GetBytes.
func (mr *MockIFallbackStorageMockRecorder) GetBytes(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBytes", reflect.TypeOf((*MockIFallbackStorage)(nil).GetBytes), key)
}

// Invalidate mocks base method.
func (m *MockIFallbackStorage) Invalidate(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockIFallbackStorageMockRecorder) Invalidate(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockIFallbackStorage)(nil).Invalidate), key)
}
