// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/jiachen/Git/mgcache/storage/bigcache/bigcache_storage.go

// Package mock_bigcache is a generated GoMock package.
package mock_bigcache

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBigcacheInterface is a mock of BigcacheInterface interface.
type MockBigcacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBigcacheInterfaceMockRecorder
}

// MockBigcacheInterfaceMockRecorder is the mock recorder for MockBigcacheInterface.
type MockBigcacheInterfaceMockRecorder struct {
	mock *MockBigcacheInterface
}

// NewMockBigcacheInterface creates a new mock instance.
func NewMockBigcacheInterface(ctrl *gomock.Controller) *MockBigcacheInterface {
	mock := &MockBigcacheInterface{ctrl: ctrl}
	mock.recorder = &MockBigcacheInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBigcacheInterface) EXPECT() *MockBigcacheInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBigcacheInterface) Delete(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBigcacheInterfaceMockRecorder) Delete(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBigcacheInterface)(nil).Delete), key)
}

// Get mocks base method.
func (m *MockBigcacheInterface) Get(key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBigcacheInterfaceMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBigcacheInterface)(nil).Get), key)
}

// Set mocks base method.
func (m *MockBigcacheInterface) Set(key string, entry []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockBigcacheInterfaceMockRecorder) Set(key, entry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockBigcacheInterface)(nil).Set), key, entry)
}
