// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/jiachen/Git/mgcache/test/mock/test/mock/codec/mock_mock_interface.go

// Package mock_mock_mock_codec is a generated GoMock package.
package mock_mock_mock_codec
