// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/jiachen/Git/mgcache/test/mock/test/mock/storage/bigcache/mock_mock_bigcache_storage.go

// Package mock_mock_mock_bigcache is a generated GoMock package.
package mock_mock_mock_bigcache
