// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/jiachen/Git/mgcache/test/mock/test/mock/storage/mock_mock_big_cache_storage.go

// Package mock_mock_mock_storage is a generated GoMock package.
package mock_mock_mock_storage
