name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ '1.15', '1.16', '1.17' ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...
